# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Card.create( number: 1, name: "Alakazam", text: "", ptype: "Psychic", rarity: "Rare", hp: 80, weakness: "Psychic", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/1.jpg")
Card.create( number: 2, name: "Blastoise", text: "", ptype: "Water", rarity: "Rare", hp: 100, weakness: "Electric", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/2.jpg")
Card.create( number: 3, name: "Chansey", text: "", ptype: "Colorless", rarity: "Rare", hp: 120, weakness: "Fighting", resistance: " P-30", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/3.jpg")
Card.create( number: 4, name: "Charizard", text: "", ptype: "Fire", rarity: "Rare", hp: 120, weakness: "Water", resistance: " F-30", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/4.jpg")
Card.create( number: 5, name: "Clefairy", text: "", ptype: "Colorless", rarity: "Rare", hp: 40, weakness: "Fighting", resistance: " P-30", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/5.jpg")
Card.create( number: 6, name: "Gyarados", text: "", ptype: "Water", rarity: "Rare", hp: 100, weakness: "Plant", resistance: " F-30", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/6.jpg")
Card.create( number: 7, name: "Hitmonchan", text: "", ptype: "Fighting", rarity: "Rare", hp: 70, weakness: "Psychic", retreatcost: 2, img_src: "https://s3.amazonaws.com/wildcards-card-images/7.jpg")
Card.create( number: 8, name: "Machamp", text: "", ptype: "Fighting", rarity: "Rare", hp: 100, weakness: "Psychic", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/8.jpg")
Card.create( number: 9, name: "Magneton", text: "", ptype: "Electric", rarity: "Rare", hp: 60, weakness: "Fighting", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/9.jpg")
Card.create( number: 10, name: "Mewtwo", text: "", ptype: "Psychic", rarity: "Rare", hp: 60, weakness: "Psychic", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/10.jpg")
Card.create( number: 11, name: "Nidoking", text: "", ptype: "Plant", rarity: "Rare", hp: 90, weakness: "Psychic", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/11.jpg")
Card.create( number: 12, name: "Ninetales", text: "", ptype: "Fire", rarity: "Rare", hp: 80, weakness: "Water", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/12.jpg")
Card.create( number: 13, name: "Poliwrath", text: "", ptype: "Water", rarity: "Rare", hp: 90, weakness: "Plant", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/13.jpg")
Card.create( number: 14, name: "Raichu", text: "", ptype: "Electric", rarity: "Rare", hp: 80, weakness: "Fighting", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/14.jpg")
Card.create( number: 15, name: "Venusaur", text: "", ptype: "Plant", rarity: "Rare", hp: 100, weakness: "Fire", retreatcost: 2, img_src: "https://s3.amazonaws.com/wildcards-card-images/15.jpg")
Card.create( number: 16, name: "Zapdos", text: "", ptype: "Electric", rarity: "Rare", hp: 90, resistance: " F-30", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/16.jpg")
Card.create( number: 17, name: "Beedrill", text: "", ptype: "Plant", rarity: "Rare", hp: 80, weakness: "Fire", resistance: " F-30", img_src: "https://s3.amazonaws.com/wildcards-card-images/17.jpg")
Card.create( number: 18, name: "Dragonair", text: "", ptype: "Colorless", rarity: "Rare", hp: 80, resistance: " P-30", retreatcost: 2, img_src: "https://s3.amazonaws.com/wildcards-card-images/18.jpg")
Card.create( number: 19, name: "Dugtrio", text: "", ptype: "Fighting", rarity: "Rare", hp: 70, weakness: "Plant", resistance: " L-30", retreatcost: 2, img_src: "https://s3.amazonaws.com/wildcards-card-images/19.jpg")
Card.create( number: 20, name: "Electabuzz", text: "", ptype: "Electric", rarity: "Rare", hp: 70, weakness: "Fighting", retreatcost: 2, img_src: "https://s3.amazonaws.com/wildcards-card-images/20.jpg")
Card.create( number: 21, name: "Electrode", text: "", ptype: "Electric", rarity: "Rare", hp: 80, weakness: "Fighting", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/21.jpg")
Card.create( number: 22, name: "Pidgeotto", text: "", ptype: "Colorless", rarity: "Rare", hp: 60, weakness: "Electric", resistance: " F-30", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/22.jpg")
Card.create( number: 23, name: "Arcanine", text: "", ptype: "Fire", rarity: "Uncommon", hp: 100, weakness: "Water", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/23.jpg")
Card.create( number: 24, name: "Charmeleon", text: "", ptype: "Fire", rarity: "Uncommon", hp: 80, weakness: "Water", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/24.jpg")
Card.create( number: 25, name: "Dewgong", text: "", ptype: "Water", rarity: "Uncommon", hp: 80, weakness: "Electric", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/25.jpg")
Card.create( number: 26, name: "Dratini", text: "", ptype: "Colorless", rarity: "Uncommon", hp: 40, resistance: " P", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/26.jpg")
Card.create( number: 27, name: "Farfetch'd", text: "", ptype: "Colorless", rarity: "Uncommon", hp: 50, weakness: "Electric", resistance: " F-30", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/27.jpg")
Card.create( number: 28, name: "Growlithe", text: "", ptype: "Fire", rarity: "Uncommon", hp: 60, weakness: "Water", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/28.jpg")
Card.create( number: 29, name: "Haunter", text: "", ptype: "Psychic", rarity: "Uncommon", hp: 60, resistance: " F", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/29.jpg")
Card.create( number: 30, name: "Ivysaur", text: "", ptype: "Plant", rarity: "Uncommon", hp: 60, weakness: "Fire", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/30.jpg")
Card.create( number: 31, name: "Jynx", text: "", ptype: "Psychic", rarity: "Uncommon", hp: 70, weakness: "Psychic", retreatcost: 2, img_src: "https://s3.amazonaws.com/wildcards-card-images/31.jpg")
Card.create( number: 32, name: "Kadabra", text: "", ptype: "Psychic", rarity: "Uncommon", hp: 60, weakness: "Psychic", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/32.jpg")
Card.create( number: 33, name: "Kakuna", text: "", ptype: "Plant", rarity: "Uncommon", hp: 80, weakness: "Fire", retreatcost: 2, img_src: "https://s3.amazonaws.com/wildcards-card-images/33.jpg")
Card.create( number: 34, name: "Machoke", text: "", ptype: "Fighting", rarity: "Uncommon", hp: 80, weakness: "Psychic", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/34.jpg")
Card.create( number: 35, name: "Magikarp", text: "", ptype: "Water", rarity: "Uncommon", hp: 30, weakness: "Electric", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/35.jpg")
Card.create( number: 36, name: "Magmar", text: "", ptype: "Fire", rarity: "Uncommon", hp: 50, weakness: "Water", retreatcost: 2, img_src: "https://s3.amazonaws.com/wildcards-card-images/36.jpg")
Card.create( number: 37, name: "Nidorino", text: "", ptype: "Plant", rarity: "Uncommon", hp: 60, weakness: "Psychic", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/37.jpg")
Card.create( number: 38, name: "Poliwhirl", text: "", ptype: "Water", rarity: "Uncommon", hp: 60, weakness: "Plant", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/38.jpg")
Card.create( number: 39, name: "Porygon", text: "", ptype: "Colorless", rarity: "Uncommon", hp: 30, weakness: "Fighting", resistance: " P", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/39.jpg")
Card.create( number: 40, name: "Raticate", text: "", ptype: "Colorless", rarity: "Uncommon", hp: 60, weakness: "Fighting", resistance: " P-30", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/40.jpg")
Card.create( number: 41, name: "Seel", text: "", ptype: "Water", rarity: "Uncommon", hp: 60, weakness: "Electric", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/41.jpg")
Card.create( number: 42, name: "Wartortle", text: "", ptype: "Water", rarity: "Uncommon", hp: 70, weakness: "Electric", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/42.jpg")
Card.create( number: 43, name: "Abra", text: "", ptype: "Psychic", rarity: "Common", hp: 30, weakness: "Psychic", img_src: "https://s3.amazonaws.com/wildcards-card-images/43.jpg")
Card.create( number: 44, name: "Bulbasaur", text: "", ptype: "Plant", rarity: "Common", hp: 40, weakness: "Fire", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/44.jpg")
Card.create( number: 45, name: "Caterpie", text: "", ptype: "Plant", rarity: "Common", hp: 40, weakness: "Fire", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/45.jpg")
Card.create( number: 46, name: "Charmander", text: "", ptype: "Fire", rarity: "Common", hp: 50, weakness: "Water", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/46.jpg")
Card.create( number: 47, name: "Diglett", text: "", ptype: "Fighting", rarity: "Common", hp: 30, weakness: "Plant", resistance: " L-30", img_src: "https://s3.amazonaws.com/wildcards-card-images/47.jpg")
Card.create( number: 48, name: "Doduo", text: "", ptype: "Colorless", rarity: "Common", hp: 50, weakness: "Electric", resistance: " F-30", img_src: "https://s3.amazonaws.com/wildcards-card-images/48.jpg")
Card.create( number: 49, name: "Drowzee", text: "", ptype: "Psychic", rarity: "Common", hp: 50, weakness: "Psychic", img_src: "https://s3.amazonaws.com/wildcards-card-images/49.jpg")
Card.create( number: 50, name: "Gastly", text: "", ptype: "Psychic", rarity: "Common", hp: 30, resistance: " F-30", img_src: "https://s3.amazonaws.com/wildcards-card-images/50.jpg")
Card.create( number: 51, name: "Koffing", text: "", ptype: "Plant", rarity: "Common", hp: 50, weakness: "Psychic", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/51.jpg")
Card.create( number: 52, name: "Machop", text: "", ptype: "Fighting", rarity: "Common", hp: 50, weakness: "Psychic", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/52.jpg")
Card.create( number: 53, name: "Magnemite", text: "", ptype: "Electric", rarity: "Common", hp: 40, weakness: "Fighting", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/53.jpg")
Card.create( number: 54, name: "Metapod", text: "", ptype: "Plant", rarity: "Common", hp: 70, weakness: "Fire", retreatcost: 2, img_src: "https://s3.amazonaws.com/wildcards-card-images/54.jpg")
Card.create( number: 55, name: "Nidoran M", text: "", ptype: "Plant", rarity: "Common", hp: 40, weakness: "Psychic", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/55.jpg")
Card.create( number: 56, name: "Onix", text: "", ptype: "Fighting", rarity: "Common", hp: 90, weakness: "Plant", retreatcost: 3, img_src: "https://s3.amazonaws.com/wildcards-card-images/56.jpg")
Card.create( number: 57, name: "Pidgey", text: "", ptype: "Colorless", rarity: "Common", hp: 40, weakness: "Electric", resistance: " F-30", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/57.jpg")
Card.create( number: 58, name: "Pikachu", text: "", ptype: "Electric", rarity: "Common", hp: 40, weakness: "Fighting", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/58.jpg")
Card.create( number: 59, name: "Poliwag", text: "", ptype: "Water", rarity: "Common", hp: 40, weakness: "Plant", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/59.jpg")
Card.create( number: 60, name: "Ponyta", text: "", ptype: "Fire", rarity: "Common", hp: 40, weakness: "Water", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/60.jpg")
Card.create( number: 61, name: "Rattata", text: "", ptype: "Colorless", rarity: "Common", hp: 30, weakness: "Fighting", resistance: " P-30", img_src: "https://s3.amazonaws.com/wildcards-card-images/61.jpg")
Card.create( number: 62, name: "Sandshrew", text: "", ptype: "Fighting", rarity: "Common", hp: 40, weakness: "Plant", resistance: " L-30", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/62.jpg")
Card.create( number: 63, name: "Squirtle", text: "", ptype: "Water", rarity: "Common", hp: 40, weakness: "Electric", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/63.jpg")
Card.create( number: 64, name: "Starmie", text: "", ptype: "Water", rarity: "Common", hp: 60, weakness: "Electric", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/64.jpg")
Card.create( number: 65, name: "Staryu", text: "", ptype: "Water", rarity: "Common", hp: 40, weakness: "Electric", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/65.jpg")
Card.create( number: 66, name: "Tangela", text: "", ptype: "Plant", rarity: "Common", hp: 50, weakness: "Fire", retreatcost: 2, img_src: "https://s3.amazonaws.com/wildcards-card-images/66.jpg")
Card.create( number: 67, name: "Voltorb", text: "", ptype: "Electric", rarity: "Common", hp: 40, weakness: "Fighting", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/67.jpg")
Card.create( number: 68, name: "Vulpix", text: "", ptype: "Fire", rarity: "Common", hp: 50, weakness: "Water", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/68.jpg")
Card.create( number: 69, name: "Weedle", text: "", ptype: "Plant", rarity: "Common", hp: 40, weakness: "Fire", retreatcost: 1, img_src: "https://s3.amazonaws.com/wildcards-card-images/69.jpg")
Card.create( number: 70, name: "Clefairy Doll", text: "", ptype: "", rarity: "Rare", hp: 10, img_src: "https://s3.amazonaws.com/wildcards-card-images/70.jpg")
Card.create( number: 71, name: "Computer Search", text: "", ptype: "", rarity: "Rare", img_src: "https://s3.amazonaws.com/wildcards-card-images/71.jpg")
Card.create( number: 72, name: "Devolution Spray", text: "", ptype: "", rarity: "Rare", img_src: "https://s3.amazonaws.com/wildcards-card-images/72.jpg")
Card.create( number: 73, name: "Impostor Professor Oak", text: "", ptype: "", rarity: "Rare", img_src: "https://s3.amazonaws.com/wildcards-card-images/73.jpg")
Card.create( number: 74, name: "Item Finder", text: "", ptype: "", rarity: "Rare", img_src: "https://s3.amazonaws.com/wildcards-card-images/74.jpg")
Card.create( number: 75, name: "Lass", text: "", ptype: "", rarity: "Rare", img_src: "https://s3.amazonaws.com/wildcards-card-images/75.jpg")
Card.create( number: 76, name: "Pokemon Breeder", text: "", ptype: "", rarity: "Rare", img_src: "https://s3.amazonaws.com/wildcards-card-images/76.jpg")
Card.create( number: 77, name: "Pokemon Trader", text: "", ptype: "", rarity: "Rare", img_src: "https://s3.amazonaws.com/wildcards-card-images/77.jpg")
Card.create( number: 78, name: "Scoop Up", text: "", ptype: "", rarity: "Rare", img_src: "https://s3.amazonaws.com/wildcards-card-images/78.jpg")
Card.create( number: 79, name: "Super Energy Removal", text: "", ptype: "", rarity: "Rare", img_src: "https://s3.amazonaws.com/wildcards-card-images/79.jpg")
Card.create( number: 80, name: "Defender", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/80.jpg")
Card.create( number: 81, name: "Energy Retrieval", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/81.jpg")
Card.create( number: 82, name: "Full Heal", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/82.jpg")
Card.create( number: 83, name: "Maintenance", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/83.jpg")
Card.create( number: 84, name: "PlusPower", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/84.jpg")
Card.create( number: 85, name: "Pokemon Center", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/85.jpg")
Card.create( number: 86, name: "Pokémon Flute", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/86.jpg")
Card.create( number: 87, name: "Pokédex", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/87.jpg")
Card.create( number: 88, name: "Professor Oak", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/88.jpg")
Card.create( number: 89, name: "Revive", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/89.jpg")
Card.create( number: 90, name: "Super Potion", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/90.jpg")
Card.create( number: 91, name: "Bill", text: "", ptype: "", rarity: "Common", img_src: "https://s3.amazonaws.com/wildcards-card-images/91.jpg")
Card.create( number: 92, name: "Energy Removal", text: "", ptype: "", rarity: "Common", img_src: "https://s3.amazonaws.com/wildcards-card-images/92.jpg")
Card.create( number: 93, name: "Gust of Wind", text: "", ptype: "", rarity: "Common", img_src: "https://s3.amazonaws.com/wildcards-card-images/93.jpg")
Card.create( number: 94, name: "Potion", text: "", ptype: "", rarity: "Common", img_src: "https://s3.amazonaws.com/wildcards-card-images/94.jpg")
Card.create( number: 95, name: "Switch", text: "", ptype: "", rarity: "Common", img_src: "https://s3.amazonaws.com/wildcards-card-images/95.jpg")
Card.create( number: 96, name: "Double Colorless Energy", text: "", ptype: "", rarity: "Uncommon", img_src: "https://s3.amazonaws.com/wildcards-card-images/96.jpg")
Card.create( number: 97, name: "Fighting Energy", text: "", ptype: "", rarity: "Common", img_src: "https://s3.amazonaws.com/wildcards-card-images/97.jpg")
Card.create( number: 98, name: "Fire Energy", text: "", ptype: "", rarity: "Common", img_src: "https://s3.amazonaws.com/wildcards-card-images/98.jpg")
Card.create( number: 99, name: "Grass Energy", text: "", ptype: "", rarity: "Common", img_src: "https://s3.amazonaws.com/wildcards-card-images/99.jpg")
Card.create( number: 100, name: "Lightning Energy", text: "", ptype: "", rarity: "Common", img_src: "https://s3.amazonaws.com/wildcards-card-images/100.jpg")
Card.create( number: 101, name: "Psychic Energy", text: "", ptype: "", rarity: "Common", img_src: "https://s3.amazonaws.com/wildcards-card-images/101.jpg")
Card.create( number: 102, name: "Water Energy", text: "", ptype: "", rarity: "Common", img_src: "https://s3.amazonaws.com/wildcards-card-images/102.jpg")
